language: groovy
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - hotfix
  - develop
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: cajQCfACpPY+ta6n+Chg12xmrIE/+NuJdjb4dyCCkWDzJffb7rNNg/ugfmAA89GNowuXPs6PBN8WUiESJm2ilSGasheOFmK5j029rmeTHvFym1au7s3Etr1hX+ZqXOtnu7naqorihwLVTG0LmHMv23Gim74iKEb4pi4h/rIW+/RkHF1v6rfllPmOmBWug6ZzHEcIvmobUJuGTiH4ySQSse5YN8J+8WgzC+hNVxafE5pTnHK3MGBjYQCpHUbUZC7Ws0G1OHP2BJTvTBrLqmuwaaxUQMOM30as7UL43wU03yofSzAc4EqaIs0uSN7kJ529yRtQUZIf4uR3eYLAbiIvl5AVnkAKjHj5L9aAqfAh/b3gl4p0nWCBV+5PyMfMj2yAdFJxWpwSwb0fMih7geBiU1OFLTa8cm/Kk9OXa9hfsBErZQ6z7ZQ7XJNmqqRq+YqzMVXXvc14nTRVLnjkLfDrxojmW7At3V9uLe74uGcBn29JfSXfKIs1fa+ZodA03fCdLLeyjxmipOqWm8Wdeuo16Xj1iBmPqtroCUmTgNG1RYFWJsJXNyC/IaQsl9Jg+HUxzxR4h6BkZ0EfKt1mfCtkNEE673CBXHRtFbUd4CN6fmKQSDW5gb4nowS/7AfOSgst5dg8AG7Nvcy9zOLA2YtuuiVyYB2gQWIw2mZKH+0O/8o=
  - secure: UCrJatVML6NdLLpT38M7OEhGGLZ7AHPCVMKW1Di5UlWa5zpZAuMVA8HpNpVU0UgC5t5WEhHGo79LHQYd6z4qmRqYTBV+x8Y6V5QU6aBwoUvSZfjL97DywvIm5i7oBdfdGiBInveZgA+82u+ij53Alrgdb5MFG3bbsyt/voP9DjcYDFccWGtzdoKOQs03CwcXmDR7CBMf7FHgVNOqpcvXrDGapZ7TGu4Bf3OEfMWi9aF4b6eKzeQFEmCcxzXwwaqr85iZQ0jD70OPQOcv8bXSpa4DeC0gku9eX28K0sQ7W0QG8qNM4XTUpDJyKuzdvLQKMCq425ZtU4JqSDuKjmYK2P9e13oFcIT/DMKEz0/EEul3tqVLVZueSYf/oej06SWEWTbmY44IX6JMrURl373dRyLq+bL40v7PgHr/nT9SQHIq/FsQhFEk0wOwZLwfz3yVJDE6Wo0TGyN5oMSIxMQkkpnU1MWeIqscHinv0fe7QX39yFze83jXL+pkSSPivnzWe45qUYu6NHK0bS4XXUP1NIoLhkW3Hn8M80U4/EX7B9NqSNPMIygrWXN+G4nzgybpI4BU9p+xTjOf2aEVUSb5QSpfmd+VKyC1MXROWbs/3VN3CjPpMp4KKiYBCM/rCXCNk5ZfirzaSVwKlnKoNQg6v3xKkUoBFPwNHX4sCDhRPks=
