---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.dataqualityfilter
    config:
        locations:
            - file:/data/dataquality-filter/config/dataquality-filter.properties
    spring:
        transactionManagement:
            proxies: false
        bean:
            packages: # packages to include in Spring bean scanning
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cache:
        ehcache:
            ehcacheXmlLocation: 'classpath:ehcache.xml'
            lockTimeout: 200 # In milliseconds
    plugins:
        twitterbootstrap:
            fixtaglib: true
    web:
        disable:
            multipart: false # whether to disable processing of multi part requests
    mime:
        disable:
            accept:
                header:
                    userAgents: #The ACCEPT header will not be used for content negotiation for user agents containing the following strings (defaults to the 4 major rendering engines)
                        - 'Gecko'
                        - 'WebKit'
                        - 'Presto'
                        - 'Trident'
        types: # the first one is the default format
            all: '*/*' # 'all' maps to '*' or the first available format in withFormat
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        # The default scope for controllers. May be prototype, session or singleton.
        # If unspecified, controllers are prototype scoped.
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html # Legacy setting for codec used to encode data with ${}
        gsp:
            encoding: UTF-8
            htmlcodec: xml # use xml escaping instead of HTML4 escaping
            codecs:
                expression: html # escapes values inside ${}
                scriptlets: html # escapes output from scriptlets in GSPs
                taglib: none # escapes output from taglibs
                staticparts: none # escapes output from static template parts
    scaffolding:
        templates:
            domainSuffix: 'Instance' # scaffolding templates configuration
    json:
        legacy:
            builder: false # Set to false to use the new Grails 1.2 JSONBuilder in the render method
    enable:
        native2ascii: true # enabled native2ascii conversion of i18n properties files
    exceptionresolver:
        params:
            exclude:
                - 'password' # request parameters to mask when logging exceptions
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

skin:
    layout: "main"
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"

privacyPolicy: "http://www.ala.org.au/about/terms-of-use/privacy-policy/"


hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
database:
    directory: "/data/dataquality-filter/database"

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dbCreate: "update"
    url: "jdbc:h2:file:${database.directory};MVCC=TRUE"

headerAndFooter:
    version: "1"

security:
    cas:
        uriFilterPattern: '/profiles,/filters/*,/download.*'
        authenticateOnlyIfLoggedInPattern: '/occurrences/(?!.+userAssertions|facet.+).+,/explore/your-area,/query,/proxy/download/.*'
        uriExclusionFilterPattern: '/occurrences/shapeUpload,/images.*,/css.*,/js.*,.*json,/help/.*'

server:
    contextPath: '/dataquality-filter'
    port: 8090

environments:
    development:
        grails:
            serverURL: "http://dev.ala.org.au:8090/dataquality-filter"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    test:
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    production:
        grails:
            serverURL: "https://biocache.ala.org.au"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"

biocache:
    indexedFieldsUrl: "${biocache.baseUrl}/index/fields"